version: '2.1'
  
services:

  page-check:
    image: nowsci/page-check:node
    container_name: page-check-node
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      CHECKS: '[
                    {
                        "url": "https://www.url.com",
                        "string": "Content to look for",
                        "reverse": false
                    }
                ]'
      PUSHOVERAPI: ''
      PUSHOVERUSER: ''
      INTERVALMIN: 10
      SMTPSERVER: ''
      SMTPFROM: ''
      SMTPTO: ''
    restart: "always"
